import type { EducationalCenter, InventoryDistribution, PaymentCollection } from '../types';

export const EGYPTIAN_GOVERNORATES: string[] = [
  'Cairo',
  'Giza',
  'Alexandria',
  'Dakahlia',
  'Red Sea',
  'Beheira',
  'Fayoum',
  'Gharbia',
  'Ismailia',
  'Menofia',
  'Minya',
  'Qaliubiya',
  'New Valley',
  'Suez',
  'Aswan',
  'Assiut',
  'Beni Suef',
  'Port Said',
  'Damietta',
  'Sharkia',
  'South Sinai',
  'Kafr El Sheikh',
  'Matrouh',
  'Luxor',
  'Qena',
  'North Sinai',
  'Sohag'
];

export const INITIAL_CENTERS: EducationalCenter[] = [
  {
    id: 'cnt-01',
    name: 'Al-Nour Educational Center (Dokki)',
    governorate: 'Giza',
    city: 'Dokki',
    contact_person: 'Mr. Mahmoud Tarek (Manager)',
    phone: '01012345678',
    book_price: 400,
    book_center_cut: 50,
    code_price: 250,
    code_center_cut: 30,
    created_at: '2026-09-01T10:00:00Z',
  },
  {
    id: 'cnt-02',
    name: 'Oxford Academy Center (Nasr City)',
    governorate: 'Cairo',
    city: 'Nasr City',
    contact_person: 'Capt. Hany Farag',
    phone: '01123456789',
    book_price: 400,
    book_center_cut: 60,
    code_price: 250,
    code_center_cut: 40,
    created_at: '2026-09-05T10:00:00Z',
  },
  {
    id: 'cnt-03',
    name: 'Elite Stars Center (Smouha)',
    governorate: 'Alexandria',
    city: 'Smouha',
    contact_person: 'Dr. Sherif Adel',
    phone: '01234567890',
    book_price: 450,
    book_center_cut: 50,
    code_price: 300,
    code_center_cut: 50,
    created_at: '2026-09-10T10:00:00Z',
  },
  {
    id: 'cnt-04',
    name: 'Al-Safwa Center (Mansoura)',
    governorate: 'Dakahlia',
    city: 'Mansoura',
    contact_person: 'Eng. Mostafa Nour',
    phone: '01099887766',
    book_price: 400,
    book_center_cut: 40,
    code_price: 200,
    code_center_cut: 25,
    created_at: '2026-09-15T10:00:00Z',
  },
  {
    id: 'cnt-05',
    name: 'Future Leaders Center (Tanta)',
    governorate: 'Gharbia',
    city: 'Tanta',
    contact_person: 'Mr. Yasser Abdelrahman',
    phone: '01511223344',
    book_price: 400,
    book_center_cut: 50,
    code_price: 250,
    code_center_cut: 30,
    created_at: '2026-09-20T10:00:00Z',
  },
];

export const INITIAL_DISTRIBUTIONS: InventoryDistribution[] = [
  {
    id: 'dist-101',
    center_id: 'cnt-01',
    center_name: 'Al-Nour Educational Center (Dokki)',
    assistant_id: 'ast-01',
    assistant_name: 'Sarah Mohamed (Assistant)',
    books_count: 200,
    codes_count: 200,
    notes: 'Delivered Term 1 comprehensive physics book & platform codes',
    distribution_date: '2026-09-15',
    created_at: '2026-09-15T11:00:00Z',
  },
  {
    id: 'dist-102',
    center_id: 'cnt-01',
    center_name: 'Al-Nour Educational Center (Dokki)',
    assistant_id: 'ast-02',
    assistant_name: 'Kareem Nabil (Assistant)',
    books_count: 100,
    codes_count: 50,
    notes: 'Mid-term replenishment batch',
    distribution_date: '2026-09-25',
    created_at: '2026-09-25T14:30:00Z',
  },
  {
    id: 'dist-103',
    center_id: 'cnt-02',
    center_name: 'Oxford Academy Center (Nasr City)',
    assistant_id: 'ast-01',
    assistant_name: 'Sarah Mohamed (Assistant)',
    books_count: 150,
    codes_count: 150,
    notes: 'Handed over to center front desk',
    distribution_date: '2026-09-18',
    created_at: '2026-09-18T10:15:00Z',
  },
  {
    id: 'dist-104',
    center_id: 'cnt-03',
    center_name: 'Elite Stars Center (Smouha)',
    assistant_id: 'ast-02',
    assistant_name: 'Kareem Nabil (Assistant)',
    books_count: 120,
    codes_count: 100,
    notes: 'Received by Dr. Sherif',
    distribution_date: '2026-09-22',
    created_at: '2026-09-22T13:00:00Z',
  },
  {
    id: 'dist-105',
    center_id: 'cnt-04',
    center_name: 'Al-Safwa Center (Mansoura)',
    assistant_id: 'ast-01',
    assistant_name: 'Sarah Mohamed (Assistant)',
    books_count: 80,
    codes_count: 80,
    notes: 'Standard batch dispatch',
    distribution_date: '2026-09-28',
    created_at: '2026-09-28T09:45:00Z',
  },
];

export const INITIAL_COLLECTIONS: PaymentCollection[] = [
  {
    id: 'col-201',
    center_id: 'cnt-01',
    center_name: 'Al-Nour Educational Center (Dokki)',
    assistant_id: 'ast-01',
    assistant_name: 'Sarah Mohamed (Assistant)',
    amount_collected: 70000,
    category: 'books',
    books_portion: 70000,
    codes_portion: 0,
    payment_method: 'instapay',
    receipt_proof_url: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&q=80&w=1000',
    notes: 'InstaPay reference #IPN-984129 for first 200 books partial settlement',
    collection_date: '2026-09-30',
    status: 'verified',
    created_at: '2026-09-30T16:00:00Z',
  },
  {
    id: 'col-202',
    center_id: 'cnt-02',
    center_name: 'Oxford Academy Center (Nasr City)',
    assistant_id: 'ast-02',
    assistant_name: 'Kareem Nabil (Assistant)',
    amount_collected: 45000,
    category: 'both',
    books_portion: 25000,
    codes_portion: 20000,
    payment_method: 'vodafone_cash',
    receipt_proof_url: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&q=80&w=1000',
    notes: 'Vodafone cash transfer received from manager (25k books + 20k codes)',
    collection_date: '2026-10-01',
    status: 'pending_verification',
    created_at: '2026-10-01T12:20:00Z',
  },
  {
    id: 'col-203',
    center_id: 'cnt-03',
    center_name: 'Elite Stars Center (Smouha)',
    assistant_id: 'ast-02',
    assistant_name: 'Kareem Nabil (Assistant)',
    amount_collected: 35000,
    category: 'codes',
    books_portion: 0,
    codes_portion: 35000,
    payment_method: 'cash',
    receipt_proof_url: null,
    notes: 'Cash handed in sealed envelope for platform activation codes',
    collection_date: '2026-10-02',
    status: 'verified',
    created_at: '2026-10-02T15:00:00Z',
  },
];
